version: "2"
run:
  tests: false

linters:
  enable:
    - gomodguard_v2
  disable:
    - gomodguard
    - err113
    - tagliatelle
    - mnd
    - dupl
    - revive
    - wsl
    - noinlineerr
    - depguard
    - exhaustruct
    - ireturn
    - lll
    - musttag
    - perfsprint
    - tagalign
    - varnamelen

settings:
  govet:
    disable:
      - fieldalignment

issues:
  exclude-dirs:
    - vendor
  exclude-generated: lax
  exclude-case: false
  exclude:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclude-generated: lax
