entries:
    - name: Terminal
      icon: utilities-terminal
      command: mate-terminal
    - separator: true
    - name: Files
      icon: system-file-manager
      command: caja .
    - name: Text Editor
      icon: accessories-text-editor
      command: pluma %U
